version: 1.0.{build}
image: Ubuntu2004

branches:
  only:
    - develop

clone_folder: ~/hello
environment:
  DJGPP_DL_LOC: /tmp/djgpp/
  DJGPP_DL: http://www.mirrorservice.org/sites/ftp.delorie.com/pub/djgpp/current/
  SDL_VIDEODRIVER: dummy
  DEVKITPRO: /opt/devkitpro
  DEVKITARM: /opt/devkitpro/devkitARM
  DEVKITPPC: /opt/devkitpro/devkitPPC
install:
  - sh: >-
      chmod +x scripts/ci.sh

      scripts/ci.sh
cache: /opt
build_script:
  - sh: >-
      make linux

      make dos

      make nds

      tree build
artifacts:
  - name: Hello World Linux
    path: build/run/Hello_World
  - name: Hello World Nintendo DS
    path: build/run/Hello World.nds
  - name: Hello World MS-DOS
    path: build/run/HELLO.EXE
  - name: Hello World Wii (Dolphin)
    path: build/run/Hello World (Wii).dol
  - name: Hello World Wii (Homebrew)
    path: build/run/Hello World (Wii).7z
