version: 1.0.{build}
image: Previous Ubuntu1604
clone_folder: ~/hello
environment:
  DJGPP_DL_LOC: /tmp/djgpp
  DJGPP_DL: http://www.mirrorservice.org/sites/ftp.delorie.com/pub/djgpp/current/
install:
  - sh: >-
      chmod +x scripts/ci.sh

      scripts/ci.sh
build_script:
  - sh: >-
      make linux

      make dos
artifacts:
  - path: build/run/hello
    name: Hello World Linux
  - path: build/run/hello.nds
    name: Hello World Nintendo DS
  - path: build/run/HELLO.EXE
    name: Hello World MS-DOS
